
version: '{build}'

branches:
  only:
    - master
    - develop
    - support/appveyor


image:
  - Visual Studio 2017

platform:
  - x86
  - x64

# configuration:
#   - Debug
#   - Release

init:
  - cmake --version
  - msbuild /version

before_build:
  - ps: |
      git submodule update --init --recursive
      mkdir build
      cd  build
      $env:generator="Visual Studio 15 2017"
      if ($env:PLATFORM -eq "x64") {
        $env:generator="$env:generator Win64"
      }
      cmake .. -G "$env:generator" -DNO_TESTS=ON

build_script:
  - ps: |
      cmake --build .  -- /m /v:minimal
